### ISSUE TITLE
Documentation: Contributors list is empty

### ISSUE THREAD

**Issue by LopezMDidac** [ERNI-Academy/assets-iac-terraform-azure#4]
### Explain in 1-2 sentences. Say what this is about.

Please add contributors to this repository

### Motivation Goals

-

### In scope

-

### Out of scope

-

### Risks / unknowns

-

**Comment by Rabosa616** [comment]
Hey @all-contributors please add @omaramalfi for code, content, doc, design, ideas, maintenance, test, example, review

**Comment by Rabosa616** [comment]
Hey @all-contributors please add @rabosa616 for code, content, doc, design, ideas, maintenance, test, example, review

**Comment by Rabosa616** [comment]
Hey @all-contributors please add @albertinisg for code, content, doc, design, ideas, maintenance, test, example, review

**Comment by Rabosa616** [comment]
Done

**Comment by LopezMDidac** [comment]
issue closed
