### ISSUE TITLE
Repository naming convention

### ISSUE THREAD

**Issue by LopezMDidac** [ERNI-Academy/assets-iac-terraform-azure#5]
### Explain in 1-2 sentences. Say what this is about.

Based on our naming convention rules,
https://github.com/ERNI-Academy/awesome-resources/blob/main/CONTRIBUTING.md

the name should be {type}-{learningPath}-{description}
type should be in singular.

It should be an starterkit instead of asset?

proposed name:
starterkit-devops-iac-terraform-azure

### Motivation Goals

-

### In scope

-

### Out of scope

-

### Risks / unknowns

-

**Comment by Rabosa616** [comment]
Done, rename it to asset instead of assets

**Comment by LopezMDidac** [comment]
issue closed
